apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: dapr-dashboard
  namespace: dapr-system
spec:
  ingressClassName: nginx
  rules:
  - host: "*.com"
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: dapr-dashboard
            port:
              number: 8080
